name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Generate version tag
        id: version
        run: |
          VERSION=$(git rev-parse --short HEAD)-$(date +%Y%m%d-%H%M%S)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"

      - name: Docker Hub Login 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            guedesclaudio/wave-model-core:${{ steps.version.outputs.version }}
            guedesclaudio/wave-model-core:latest

      - name: Update GitOps repository
        run: |
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/guedesclaudio/wave-model-core-git-ops.git
          cd wave-model-core-git-ops

          sed -i "s|image: guedesclaudio/wave-model-core:.*|image: guedesclaudio/wave-model-core:${{ steps.version.outputs.version }}|g" base/deployment.yaml

          grep "guedesclaudio/wave-model-core" base/deployment.yaml

          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "🚀 Update wave-model to ${{ steps.version.outputs.version }}"
          git push

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/msc/minio-git-ops
            git pull origin main
            cd base
            kubectl apply -f .
            echo "✅ Deploy completed with version ${{ steps.version.outputs.version }}"